#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
package ${package};

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Spring Boot application entry point.
 *
 * <p>Generated by {@code spring-hexagonal-archetype} — a Maven archetype that enforces
 * hexagonal (ports-and-adapters) architecture via ArchUnit.</p>
 *
 * <p>Architecture layers:</p>
 * <ul>
 *   <li>{@code domain} — pure Java aggregate roots and value objects</li>
 *   <li>{@code application.port.in} — inbound ports (use case interfaces)</li>
 *   <li>{@code application.port.out} — outbound ports (repository interfaces)</li>
 *   <li>{@code application.service} — use case implementations</li>
 *   <li>{@code adapter.in.web} — REST inbound adapters</li>
 *   <li>{@code adapter.out.persistence} — JPA outbound adapters</li>
 * </ul>
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
